#!/bin/bash

module load pythonpackages/3.6.0/pandas/0.23.4/gnu
module load compiler/python/3.6.0/ucs4/gnu/447
module load pythonpackages/3.6.0/ucs4/gnu/447/six/1.10.0/gnu
module load apps/pythonpackages/3.6.0/tensorflow/1.9.0/gpu

python3 cnn.py $1 $2 $3